### ISSUE TITLE
x264 git address has changed

### ISSUE THREAD

**Issue by AlexKlimaj** [idlerun/rtsp-server-rpi-gstreamer#1]
https://github.com/idlerun/rtsp-server-rpi-gstreamer/blob/8fba5662f50c8f945c9d7282169b77db0435767b/Dockerfile#L39

Address needs to be changed to the following:
https://code.videolan.org/videolan/x264.git

**Comment by idlerun** [comment]
blindly accepted! (don't have a pi in a state to test it currently)
